name: appsonair_flutter_appremark
description: AppsOnAir AppRemark flutter sdk allows you to capture current screen on device shake directly through AppsOnAir.
version: 0.0.2

#homepage:
repository: https://github.com/apps-on-air/AppsOnAir-flutter-AppRemark


environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lwpackage.appsonair_flutter_appremark
        pluginClass: AppsonairFlutterAppremarkPlugin
      ios:
        pluginClass: AppsonairFlutterAppremarkPlugin